apiVersion: v1
kind: Pod
metadata:
  name: demo-secret
  labels:
    name: demo-secret
spec:
  containers:
  - name: demo-secret
    image: poznajkubernetes/pkad
    envFrom:
      - secretRef:
          name: secret-file
    volumeMounts:
      - mountPath: /secret/
        name: secret-volume
        readOnly: true
    resources: {}
    ports:
      - containerPort: 8080
  volumes:
    - name: secret-volume
      secret:
          secretName: secret-file
