apiVersion: v1
kind: PersistentVolume
metadata:
  name: pk-delete-pv
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/c/poznajkubernetes/volumes/delete"