apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fanout-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /host/?(.*)
        backend:
          serviceName: helloapp-fanout-host-svc
          servicePort: 80
      - path: /echo/?(.*)
        backend:
          serviceName: helloapp-fanout-echo-svc
          servicePort: 8080