apiVersion: v1
kind: Pod
metadata:
  name: helloapp
  labels:
    app: helloapp-ns-pod
spec:
  containers:
  - name: helloapp-ns-pod
    image: poznajkubernetes/helloapp:svc
    ports:
    - containerPort: 8080