kind: Service
apiVersion: v1
metadata:
  name: external-web
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80 
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-web
subsets: 
  - addresses:
    - ip: 1.1.1.1
    ports:
      - port: 80 
        name: http
