apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pk-default-pvc
spec:
  # storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi