apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: app1-jekins
 namespace: app1
subjects:
- kind: ServiceAccount
  name: jekins
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io