apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fix-dns
  namespace: np-pk
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector: {}