apiVersion: v1
kind: Pod
metadata:
  name: cap
  labels:
    name: cap
spec:
  containers:
  - name: cap
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      capabilities:
        drop:
          - SYS_TIME
