apiVersion: v1
kind: Pod
metadata:
  name: guest
  labels:
    name: guest
spec:
  containers:
  - name: guest
    image: alpine
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      runAsUser: 405
