apiVersion: v1
kind: Pod
metadata:
  name: non-root
  labels:
    name: non-root
spec:
  containers:
  - name: non-root
    image: busybox
    command: ["/bin/sleep", "99999"]
    securityContext:
        runAsNonRoot: true
