apiVersion: v1
kind: Pod
metadata:
  name: privilaged
  labels:
    name: privilaged
spec:
  containers:
  - name: privilaged
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      privileged: true
